site_name: Curso MikroTik
theme:
  name: material

nav:
  - Inicio: index.md
  - Bloque 1. Introducción:
      - 1. Introducción a MikroTik y RouterOS: introduccion/01_mikrotik_routeros.md
      - 2. Virtualización de RouterOS con GNS3: introduccion/02_virtualizacion_gns3.md
      - 3. Conectando a RouterOS para su administración: introduccion/03_acceso_routeros.md
  - Bloque 2. Configuración básica:
      - 1. Eliminar configuración: bloque2/eliminar.md
      - 2. Configuración de DHCP (ip dinámica): bloque2/dhcp.md
      - 3. Configuración de IP estática: bloque2/ip_estatica.md
      - 4. Configuración de bridge dinámico: bloque2/bridge_dinamico.md
      - 5. Configuración de bridge estático: bloque2/bridge_estatica.md
      - 6. Actividad práctica: bloque2/tarea_bloque2.md
  - Bloque 3. Servicios de red esenciales (DHCP y NAT):
      - 1. Configuración de DHCP Server sobre un bridge, de manera manual: bloque3/dhcp_bridge_manual.md
      - 2. Configuración de DHCP Server sobre un bridge, utilizando el asistente: bloque3/dhcp_bridge_asistente.md
      - 3. Reservas de IP en DHCP (DHCP Static Leases)l: bloque3/dhcp_reservas.md
      - 4. Configuración de NAT (Network Address Translation): bloque3/configuracion_nat.md
      - 5. Actividad práctica: bloque3/Actividad_bloque3.md
  - Bloque 4. Firewall, redirección de puertos y DMZ:
      - 1. Configuración de firewall en RouterOS: bloque4/firewall.md
      - 2. Redirección de puertos (Port Forwarding): bloque4/redireccion_puertos.md
      - 3. Configuración de DMZ (Zona Desmilitarizada): bloque4/dmz.md
      - 4. Actividad práctica: bloque4/Actividad_bloque4.md


            
      

    
  
       
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences